# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Ashish-portfolio
env:
  CI: false
  GITHUB_USERNAME: ${{ github.repository_owner }}
  REACT_APP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is automatically set by Github Actions
  USE_GITHUB_DATA: "true"
  MEDIUM_USERNAME: "CRLannister" # Change this to your medium username

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "GITHUB_USERNAME=$GITHUB_USERNAME" >> .env
        echo "REACT_APP_GITHUB_TOKEN=$REACT_APP_GITHUB_TOKEN" >> .env
        echo "USE_GITHUB_DATA=$USE_GITHUB_DATA" >> .env
        echo "MEDIUM_USERNAME=$MEDIUM_USERNAME" >> .env
      env:
        GITHUB_USERNAME: ${{ github.repository_owner }}
        REACT_APP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is automatically set by Github Actions
        USE_GITHUB_DATA: "true"
        MEDIUM_USERNAME: "CRLannister" # Change this to your medium username

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_60c9934977aa47c8b6535c78475d7c93 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_644b60dbd43e411093eeb06fef690559 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_60c9934977aa47c8b6535c78475d7c93 }}/personal_website:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Ashish-portfolio'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cecfe8fc969746f5ae0e7f71a6d6587d }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_60c9934977aa47c8b6535c78475d7c93 }}/personal_website:${{ github.sha }}'
